# Generated by Django 5.0.1 on 2024-03-26 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.AddField(
            model_name='debtor',
            name='total_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='additional_information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('SLL', 'Leones'), ('USD', 'Dollars'), ('GBP', 'Pounds')], default='SLL', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='debtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='debt_tracker.debtor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
