# Generated by Django 5.0.1 on 2024-03-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0002_remove_transaction_payment_debtor_total_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
