# Generated by Django 5.0.1 on 2024-03-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0003_debtor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
