# Generated by Django 5.0.1 on 2024-03-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0005_alter_transaction_additional_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
