# Generated by Django 5.0.1 on 2024-03-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0006_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
