# Generated by Django 5.0.1 on 2024-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0007_transaction_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
