# Generated by Django 5.0.1 on 2024-03-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0008_alter_transaction_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='additional_information',
        ),
    ]
