# Generated by Django 5.0.1 on 2024-04-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_tracker', '0010_debtor_debt_currency_alter_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='outstanding_balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
